// SPDX-License-Identifier: MIT

// Command tygo generates SDK wire DTO declarations from the Go protocol types.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"

	"github.com/gzuidhof/tygo/tygo"
)

const header = "// SPDX-License-Identifier: MIT\n// Code generated by Tygo v0.2.21 from sdk/go/protocol/types.go; DO NOT EDIT.\n// Regenerate: npm run generate:types --prefix bus\n\n"

func main() {
	check := flag.Bool("check", false, "fail if committed declarations differ from generation")
	flag.Parse()
	raw, err := os.ReadFile("../../sdk/go/protocol/types.go")
	if err == nil {
		var output []byte
		output, err = generate(raw)
		if err == nil {
			const destination = "../../sdk/js/protocol.d.ts"
			if *check {
				var existing []byte
				existing, err = os.ReadFile(destination)
				if err == nil && !bytes.Equal(existing, output) {
					err = fmt.Errorf("protocol.d.ts is stale; run npm run generate:types --prefix bus")
				}
			} else {
				err = os.WriteFile(destination, output, 0o644)
			}
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(raw []byte) ([]byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "types.go", raw, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	var source bytes.Buffer
	for _, declaration := range file.Decls {
		decl, ok := declaration.(*ast.GenDecl)
		if !ok || decl.Tok != token.TYPE {
			continue // DTO types only: never declare runtime constants the JS module does not export.
		}
		for _, spec := range decl.Specs {
			if !spec.(*ast.TypeSpec).Name.IsExported() {
				return nil, fmt.Errorf("wire type file contains an unexported type; select its public boundary explicitly")
			}
		}
		if err := format.Node(&source, fset, decl); err != nil {
			return nil, err
		}
		source.WriteString("\n\n")
	}
	output, err := tygo.ConvertGoToTypescript(source.String(), tygo.PackageConfig{
		FallbackType:     "unknown",
		TypeMappings:     map[string]string{"json.RawMessage": "unknown"},
		PreserveComments: "types",
	})
	if err != nil {
		return nil, err
	}
	// Tygo annotates unknown external types. Go 'any' is intentional open JSON,
	// but a new unmapped external type must receive an explicit wire mapping.
	if strings.Contains(output, "unknown /*") {
		return nil, fmt.Errorf("unmapped external type in generated DTOs: add an explicit wire mapping")
	}
	return []byte(header + output), nil
}
